import Navigation from "@/components/Navigation";
import { Card, CardHeader, CardTitle, CardContent} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Input } from "@/components/ui/input";
import { useState } from "react";

const VerbalReasoning = () => {
  const [searchTerm, setSearchTerm] = useState("");

  const vocabularyWords = [
    { "word": "Aberrant", "definition": "Markedly different from an accepted norm" },
    { "word": "Aberration", "definition": "A deviation from what is normal or expected" },
    { "word": "Abjure", "definition": "Formally reject or give up (as a belief)" },
    { "word": "Aboveboard", "definition": "Open and honest" },
    { "word": "Abrogate", "definition": "Revoke formally" },
    { "word": "Abstain", "definition": "Choose not to consume or take part in (particularly something enjoyable)" },
    { "word": "Abstruse", "definition": "Difficult to understand; incomprehensible" },
    { "word": "Abysmal", "definition": "Extremely bad" },
    { "word": "Accolade", "definition": "An award or praise granted as a special honor" },
    { "word": "Acerbic", "definition": "Harsh in tone" },
    { "word": "Acme", "definition": "The highest point of achievement" },
    { "word": "Acrimony", "definition": "Bitterness and ill will" },
    { "word": "Adamant", "definition": "Refusing to change one's mind" },
    { "word": "Adjudicate", "definition": "To serve as a judge in a competition; to arrive at a judgment or conclusion" },
    { "word": "Admonish", "definition": "To warn strongly, even to the point of reprimanding" },
    { "word": "Admonitory", "definition": "Serving to warn; expressing reproof or reproach especially as a corrective" },
    { "word": "Advocate", "definition": "Speak, plead, or argue in favor of (2) A person who pleads for a cause or propounds an idea" },
    { "word": "Aesthete", "definition": "One who professes great sensitivity to the beauty of art and nature" },
    { "word": "Aesthetic", "definition": "Concerned with the appreciation of beauty (2) A set of principles underlying and guiding the work of a particular artist or artistic movement" },
    { "word": "Affable", "definition": "Likeable; easy to talk to" },
    { "word": "Affluent", "definition": "Wealthy" },
    { "word": "Afford", "definition": "Provide with an opportunity" },
    { "word": "Alacrity", "definition": "An eager willingness to do something" },
    { "word": "Altruism", "definition": "The quality of unselfish concern for the welfare of others" },
    { "word": "Amalgam", "definition": "A mixture of multiple things" },
    { "word": "Ambiguous", "definition": "Open to more than one interpretation" },
    { "word": "Ambivalent", "definition": "Mixed or conflicting emotions about something" },
    { "word": "Ameliorate", "definition": "Make something bad better" },
    { "word": "Amenable", "definition": "Easily persuaded" },
    { "word": "Amiable", "definition": "Friendly" },
    { "word": "Amorphous", "definition": "Shapeless" },
    { "word": "Amply", "definition": "More than is adequate" },
    { "word": "Amuck", "definition": "In a frenzied or uncontrolled state" },
    { "word": "Anachronism", "definition": "Something that is inappropriate for the given time period (usually something old)" },
    { "word": "Analogous", "definition": "Similar in some respects but otherwise different" },
    { "word": "Anathema", "definition": "A detested person; the source of somebody's hate" },
    { "word": "Anemic", "definition": "Lacking energy and vigor" },
    { "word": "Animosity", "definition": "Intense hostility" },
    { "word": "Anodyne", "definition": "Something that soothes or relieves pain" },
    { "word": "Anomalous", "definition": "Not normal" },
    { "word": "Anomaly", "definition": "Something that is not normal, standard, or expected" },
    { "word": "Antedated", "definition": "Precede in time" },
    { "word": "Antic", "definition": "Ludicrously odd" },
    { "word": "Antipathy", "definition": "An intense feeling of dislike or aversion" },
    { "word": "Antiquated", "definition": "Old-fashioned; belonging to an earlier period in time" },
    { "word": "Antithetical", "definition": "Sharply contrasted in character or purpose" },
    { "word": "Apathetic", "definition": "Marked by a lack of interest" },
    { "word": "Apathy", "definition": "An absence of emotion or enthusiasm" },
    { "word": "Apex", "definition": "The highest point" },
    { "word": "Aphorism", "definition": "A short instructive saying about a general truth" },
    { "word": "Aphoristic", "definition": "Concise and instructive of a general truth or principle" },
    { "word": "Aplomb", "definition": "Great coolness and composure under strain" },
    { "word": "Apocryphal", "definition": "Being of questionable authenticity" },
    { "word": "Apogee", "definition": "The highest point" },
    { "word": "Apostate", "definition": "A person who has abandoned a religious faith or cause" },
    { "word": "Apothegm", "definition": "A short, pithy instructive saying" },
    { "word": "Apotheosis", "definition": "Exaltation to divine status; the highest point of development" },
    { "word": "Appease", "definition": "Pacify by acceding to the demands of" },
    { "word": "Appreciable", "definition": "Large enough to be noticed (usually refers to an amount)" },
    { "word": "Apprehension", "definition": "Fearful expectation" },
    { "word": "Approbatory", "definition": "Expressing praise or approval" },
    { "word": "Appropriate", "definition": "To give or take something by force" },
    { "word": "Appurtenant", "definition": "Supply added support" },
    { "word": "Arbitrary", "definition": "Based on a random, groundless decision" },
    { "word": "Arcane", "definition": "Requiring secret or mysterious knowledge" },
    { "word": "Arch", "definition": "To be deliberately teasing" },
    { "word": "Archaic", "definition": "So old as to appear to belong to a different period" },
    { "word": "Arduous", "definition": "Demanding considerable mental effort and skill; testing powers of endurance" },
    { "word": "Arrant", "definition": "Complete and wholly (usually modifying a noun with negative connotation)" },
    { "word": "Arriviste", "definition": "A person who has recently reached a position of power; a social climber" },
    { "word": "Arrogate", "definition": "Seize and control without authority" },
    { "word": "Artful", "definition": "Exhibiting artistic skill (2) Clever in a cunning way" },
    { "word": "Artifice", "definition": "Cunning tricks used to deceive others" },
    { "word": "Artless", "definition": "Without cunning or deceit" },
    { "word": "Ascendancy", "definition": "The state that exists when one person or group has power over another" },
    { "word": "Ascetic", "definition": "Practicing self-denial (2) One who practices great self-denial" },
    { "word": "Ascribe", "definition": "Attribute or credit to" },
    { "word": "Askance", "definition": "With a look of suspicion or disapproval" },
    { "word": "Asperity", "definition": "Harshness of manner" },
    { "word": "Assail", "definition": "Attack in speech or writing" },
    { "word": "Assiduously", "definition": "With care and persistence" },
    { "word": "Assuage", "definition": "Make something intense less severe" },
    { "word": "Atavism", "definition": "A reappearance of an earlier characteristic; throwback" },
    { "word": "Attenuate", "definition": "To weaken (in terms of intensity); to taper off or become thinner" },
    { "word": "Audacious", "definition": "Willing to be bold in social situations or to take risks" },
    { "word": "Audacity", "definition": "Aggressive boldness in social situations" },
    { "word": "Augment", "definition": "Enlarge or increase; improve" },
    { "word": "Auspicious", "definition": "Favorable, the opposite of sinister" },
    { "word": "Austere", "definition": "Practicing self-denial (2) Unadorned in style or appearance (2) Harsh in manner or temperament" },
    { "word": "Autocratic", "definition": "Characteristic of an absolute ruler or absolute rule; having absolute sovereignty" },
    { "word": "Autonomously", "definition": "In an autonomous or self-governing manner" },
    { "word": "Avarice", "definition": "Greed (one of the seven deadly sins)" },
    { "word": "Avaricious", "definition": "Excessively greedy" },
    { "word": "Avert", "definition": "Turn away (2) Ward off or prevent" },
    { "word": "Avid", "definition": "Marked by active interest and enthusiasm" },
    { "word": "Badger", "definition": "To pester" },
    { "word": "Baleful", "definition": "Threatening or foreshadowing evil or tragic developments" },
    { "word": "Balk", "definition": "Refuse to comply" },
    { "word": "Banal", "definition": "Repeated too often; overfamiliar through overuse" },
    { "word": "Banality", "definition": "A trite or obvious remark" },
    { "word": "Banish", "definition": "Expel from a community, residence, or location; drive away" },
    { "word": "Base", "definition": "The lowest, class were without any moral principles" },
    { "word": "Bastardization", "definition": "An act that debases or corrupts" },
    { "word": "Beatific", "definition": "Blissfully happy" },
    { "word": "Becoming", "definition": "Appropriate, and matches nicely" },
    { "word": "Begrudge", "definition": "To envy someone for possessing or enjoying something (2) To give reluctantly" },
    { "word": "Behooves", "definition": "To be one's duty or obligation" },
    { "word": "Belie", "definition": "To give a false representation to; misrepresent" },
    { "word": "Belittle", "definition": "Lessen the importance, dignity, or reputation of" },
    { "word": "Bellicose", "definition": "Warlike; inclined to quarrel" },
    { "word": "Belligerent", "definition": "Characteristic of one eager to fight" },
    { "word": "Bemoan", "definition": "Express discontent or a strong regret" },
    { "word": "Benighted", "definition": "Fallen into a state of ignorance" },
    { "word": "Benign", "definition": "Kind (2) (Medicine) Not dangerous to health; not recurrent or progressive" },
    { "word": "Bereft", "definition": "Unhappy in love; suffering from unrequited love" },
    { "word": "Besiege", "definition": "Harass, as with questions or requests; cause to feel distressed or worried" },
    { "word": "Besmirch", "definition": "Damage the good name and reputation of someone" },
    { "word": "Besotted", "definition": "Strongly affectionate towards" },
    { "word": "Betray", "definition": "To reveal or make known something, usually unintentionally" },
    { "word": "Bilious", "definition": "Irritable; always angry" },
    { "word": "Blatant", "definition": "Without any attempt at concealment; completely obvious" },
    { "word": "Bleak", "definition": "Having a depressing or gloomy outlook" },
    { "word": "Blinkered", "definition": "To have a limited outlook or understanding" },
    { "word": "Bolster", "definition": "Support and strengthen" },
    { "word": "Boon", "definition": "A desirable state (2) Very close and convivial" },
    { "word": "Boorish", "definition": "Ill-mannered and coarse or contemptible in behavior or appearance" },
    { "word": "Bowdlerize", "definition": "Edit by omitting or modifying parts considered indelicate" },
    { "word": "Brazen", "definition": "Unrestrained by convention or propriety" },
    { "word": "Bridle", "definition": "The act of restraining power or action or limiting excess" },
    { "word": "Bristle", "definition": "React in an offended or angry manner" },
    { "word": "Broadside", "definition": "A strong verbal attack" },
    { "word": "Bromide", "definition": "A trite or obvious remark" },
    { "word": "Brook", "definition": "Put up with something or somebody unpleasant" },
    { "word": "Browbeat", "definition": "Be bossy towards; discourage or frighten with threats or a domineering manner" },
    { "word": "Brusquely", "definition": "In a blunt, direct manner" },
    { "word": "Buck", "definition": "Resist" },
    { "word": "Bucolic", "definition": "Relating to the pleasant aspects of the country" },
    { "word": "Bumbling", "definition": "Lacking physical movement skills, especially with the hands" },
    { "word": "Burgeon", "definition": "Grow and flourish" },
    { "word": "Buttress", "definition": "Make stronger or defensible" },
    { "word": "Byzantine", "definition": "Intricate and complex" },
    { "word": "Cadaverous", "definition": "Emaciated; gaunt" },
    { "word": "Callow", "definition": "Young and inexperienced" },
    { "word": "Calumny", "definition": "Making of a false statement meant to injure a person’s reputation" },
    { "word": "Canard", "definition": "A deliberately misleading fabrication" },
    { "word": "Candid", "definition": "A straightforward and honest look at something" },
    { "word": "Candidness", "definition": "The quality of being honest and straightforward in attitude and speech" },
    { "word": "Capitulate", "definition": "To surrender (usually under agreed conditions)" },
    { "word": "Capricious", "definition": "Determined by chance or impulse rather than by necessity or reason" },
    { "word": "Cardinal", "definition": "Of primary importance; fundamental" },
    { "word": "Carping", "definition": "Persistently petty and unjustified criticism" },
    { "word": "Castigate", "definition": "To reprimand harshly" },
    { "word": "Cataclysm", "definition": "An event resulting in great loss and misfortune" },
    { "word": "Catalyst", "definition": "Something that speeds up an event" },
    { "word": "Catholic", "definition": "Of broad scope; universal" },
    { "word": "Cavalier", "definition": "Given to haughty disregard of others" },
    { "word": "Cede", "definition": "Relinquish possession or control over" },
    { "word": "Celerity", "definition": "Speed, rapidity" },
    { "word": "Censor", "definition": "To examine and remove objectionable material" },
    { "word": "Censure", "definition": "To express strong disapproval" },
    { "word": "Cerebral", "definition": "Involving intelligence rather than emotions or instinct" },
    { "word": "Chagrin", "definition": "Strong feelings of embarrassment" },
    { "word": "Champion", "definition": "Protect or fight for as a champion" },
    { "word": "Charlatan", "definition": "A flamboyant deceiver; one who attracts customers with tricks or jokes" },
    { "word": "Chary", "definition": "Cautious" },
    { "word": "Chastise", "definition": "To reprimand harshly" },
    { "word": "Chauvinism", "definition": "Fanatical patriotism; belief that one's group/cause is superior to all others" },
    { "word": "Chauvinist", "definition": "A person who believes in the superiority of their group" },
    { "word": "Check", "definition": "To limit (usually modifying the growth of something) (2) The condition of being held back or limited" },
    { "word": "Checkered", "definition": "Marked by disreputable happenings" },
    { "word": "Chimera", "definition": "Something desired or wished for but is only an illusion and impossible to achieve" },
    { "word": "Chivalrous", "definition": "Being attentive to women like an ideal knight" },
    { "word": "Choleric", "definition": "Prone to outbursts of temper; easily angered" },
    { "word": "Chortle", "definition": "To chuckle, laugh merrily" },
    { "word": "Churlish", "definition": "Lacking manners or refinement" },
    { "word": "Circumscribe", "definition": "Restrict or confine" },
    { "word": "Circumvent", "definition": "Cleverly find a way out of one's duties or obligations" },
    { "word": "Clemency", "definition": "Leniency and compassion shown toward offenders by a person or agency charged with administering justice" },
    { "word": "Coalesce", "definition": "Fuse or cause to grow together" },
    { "word": "Cogent", "definition": "Clear and persuasive" },
    { "word": "Cohesive", "definition": "Well integrated, forming a united whole" },
    { "word": "Collusion", "definition": "Agreement on a secret plot" },
    { "word": "Colossal", "definition": "So great in size or force or extent as to elicit awe" },
    { "word": "Commendable", "definition": "Worthy of high praise" },
    { "word": "Commensurate", "definition": "To be in proportion or corresponding in degree or amount" },
    { "word": "Complacent", "definition": "Contented to a fault with oneself or one's actions" },
    { "word": "Complaisant", "definition": "Showing a cheerful willingness to do favors for others" },
    { "word": "Complementary", "definition": "Enhancing each other's qualities (for two things or more)" },
    { "word": "Complicit", "definition": "Associated with or participating in an activity, especially one of a questionable nature" },
    { "word": "Concede", "definition": "Acknowledge defeat (2) Admit (to a wrongdoing) (2) Give over; surrender or relinquish to the physical control of another" },
    { "word": "Conciliate", "definition": "To make peace with" },
    { "word": "Concomitant", "definition": "Describing an event or situation that happens at the same time as or in connection with another" },
    { "word": "Conflagration", "definition": "A very intense and uncontrolled fire" },
    { "word": "Conflate", "definition": "Mix together different elements or concepts" },
    { "word": "Confound", "definition": "Be confusing or perplexing to (2) Mistake one thing for another" },
    { "word": "Conspicuous", "definition": "Without any attempt at concealment; completely obvious" },
    { "word": "Constituent", "definition": "A citizen who is represented in a government by officials for whom he or she votes (2) An abstract part of something" },
    { "word": "Construe", "definition": "Interpreted in a particular way" },
    { "word": "Contentious", "definition": "Likely to argue" },
    { "word": "Contingent", "definition": "A gathering of persons representative of some larger group (2) Possible but not certain to occur" },
    { "word": "Contrition", "definition": "The feeling of remorse or guilt that comes from doing something bad" },
    { "word": "Contrive", "definition": "To pull off a plan or scheme, usually through skill or trickery" },
    { "word": "Copious", "definition": "In abundant supply" },
    { "word": "Corollary", "definition": "A practical consequence that follows naturally" },
    { "word": "Cosseted", "definition": "Treat with excessive indulgence" },
    { "word": "Coterminous", "definition": "Being of equal extent or scope or duration" },
    { "word": "Countermand", "definition": "A contrary command canceling or reversing a previous command" },
    { "word": "Cow", "definition": "To intimidate" },
    { "word": "Craven", "definition": "Pathetically cowardly" },
    { "word": "Crestfallen", "definition": "Brought low in spirit" },
    { "word": "Cryptic", "definition": "Mysterious or vague, usually intentionally" },
    { "word": "Crystallize", "definition": "Cause to take on a definite and clear shape" },
    { "word": "Culminate", "definition": "Reach the highest or most decisive point" },
    { "word": "Culpability", "definition": "A state of guilt" },
    { "word": "Cupidity", "definition": "Greed for money" },
    { "word": "Curmudgeon", "definition": "A grouchy, surly person" },
    { "word": "Debonair", "definition": "Having a sophisticated charm" },
    { "word": "Decorous", "definition": "Characterized by good taste in manners and conduct" },
    { "word": "Decorum", "definition": "Propriety in manners and conduct" },
    { "word": "Decry", "definition": "Express strong disapproval of" },
    { "word": "Deferential", "definition": "Showing respect" },
    { "word": "Defray", "definition": "To help pay the cost of, either in part or full" },
    { "word": "Deign", "definition": "Do something that one considers to be below one's dignity" },
    { "word": "Deleterious", "definition": "Harmful to living things" },
    { "word": "Delineate", "definition": "Describe in detail" },
    { "word": "Demonstrative", "definition": "Given to or marked by the open expression of emotion" },
    { "word": "Demur", "definition": "To object or show reluctance" },
    { "word": "Denigrate", "definition": "Charge falsely or with malicious intent; attack the good name and reputation of someone" },
    { "word": "Denote", "definition": "Be a sign or indication of; have as a meaning" },
    { "word": "Denouement", "definition": "The final resolution of the many strands of a literary or dramatic work; the outcome of a complex sequence of events" },
    { "word": "Derelict", "definition": "(of a person) not doing one's duties (2) (of a building) abandoned" },
    { "word": "Derivative", "definition": "Not original but drawing on the work of another person" },
    { "word": "Derive", "definition": "Come from; be connected by a relationship of blood, for example (2) Reason by deduction; establish by deduction" },
    { "word": "Desiccated", "definition": "Uninteresting, lacking vitality" },
    { "word": "Desideratum", "definition": "Something desired as a necessity" },
    { "word": "Despot", "definition": "A cruel and oppressive dictator" },
    { "word": "Diatribe", "definition": "A strong verbal attack against a person or institution" },
    { "word": "Dictatorial", "definition": "Expecting unquestioning obedience; characteristic of an absolute ruler" },
    { "word": "Didactic", "definition": "Instructive (especially excessively)" },
    { "word": "Diffident", "definition": "Showing modest reserve; lacking self-confidence" },
    { "word": "Dilatory", "definition": "Wasting time" },
    { "word": "Dilettante", "definition": "An amateur who engages in an activity without serious intentions and who pretends to have knowledge" },
    { "word": "Diminutive", "definition": "To indicate smallness (2) Very small" },
    { "word": "Disabuse", "definition": "To persuade somebody that his/her belief is not valid" },
    { "word": "Disaffected", "definition": "Discontented as toward authority" },
    { "word": "Discrete", "definition": "Constituting a separate entity or part" },
    { "word": "Discursive", "definition": "(of speech and writing) tending to depart from the main point" },
    { "word": "Disingenuous", "definition": "Not straightforward; giving a false appearance of frankness" },
    { "word": "Disinterested", "definition": "Unbiased; neutral" },
    { "word": "Dispassionate", "definition": "Unaffected by strong emotion or prejudice" },
    { "word": "Dispensation", "definition": "An exemption from a rule or obligation" },
    { "word": "Dissemble", "definition": "Conceal one's true motives, usually through deceit" },
    { "word": "Disseminate", "definition": "Cause to become widely known" },
    { "word": "Dissipate", "definition": "Squander or spend money frivolously (2) To disperse or scatter" },
    { "word": "Dissolution", "definition": "A living full of debauchery and indulgence in sensual pleasure" },
    { "word": "Dogmatic", "definition": "Highly opinionated, not accepting that your belief may not be correct" },
    { "word": "Doleful", "definition": "Filled with or evoking sadness" },
    { "word": "Dolorous", "definition": "Showing sorrow" },
    { "word": "Doughty", "definition": "Brave; bold; courageous" },
    { "word": "Dovetail", "definition": "Fit together tightly, as if by means of an interlocking joint" },
    { "word": "Duplicity", "definition": "Deceitfulness, pretending to want one thing but interested in something else" },
    { "word": "Duress", "definition": "Compulsory force or threat" },
    { "word": "Ebullient", "definition": "Joyously unrestrained" },
    { "word": "Eccentric", "definition": "Highly unconventional or unusual (usually describes a person)" },
    { "word": "Eclectic", "definition": "Comprised of a variety of styles" },
    { "word": "Economical", "definition": "Avoiding waste, efficient" },
    { "word": "Edifying", "definition": "Enlightening or uplifting so as to encourage intellectual or moral improvement" },
    { "word": "Effervescent", "definition": "Marked by high spirits or excitement" },
    { "word": "Efficacious", "definition": "Producing the intended result" },
    { "word": "Effrontery", "definition": "Audacious (even arrogant) behavior that you have no right to" },
    { "word": "Egotist", "definition": "A conceited and self-centered person" },
    { "word": "Egregious", "definition": "Standing out in a negative way; shockingly bad" },
    { "word": "Eke", "definition": "To live off meager resources, to scrape by" },
    { "word": "Elaborate", "definition": "Marked by complexity and richness of detail (2) Explain in more detail" },
    { "word": "Elegiac", "definition": "Expressing sorrow" },
    { "word": "Elicit", "definition": "Call forth (emotions, feelings, and responses)" },
    { "word": "Elucidate", "definition": "Make clearer and easier to understand" },
    { "word": "Elude", "definition": "Escape understanding" },
    { "word": "Elusive", "definition": "Difficult to capture or difficult to remember" },
    { "word": "Embellish", "definition": "Make more attractive by adding ornament, color, etc.; make more beautiful" },
    { "word": "Embroiled", "definition": "Involved in argument or contention" },
    { "word": "Embryonic", "definition": "In an early stage of development" },
    { "word": "Eminent", "definition": "Standing above others in quality or position" },
    { "word": "Empathetic", "definition": "Showing understanding and ready comprehension of other people's states and emotions" },
    { "word": "Empiricism", "definition": "Any method that derives knowledge from experience, used in experimental science" },
    { "word": "Emulate", "definition": "Strive to equal or match, especially by imitating; compete with successfully" },
    { "word": "Enamor", "definition": "Attraction or feeling of love" },
    { "word": "Encumber", "definition": "Hold back" },
    { "word": "Endemic", "definition": "Native; originating where it is found" },
    { "word": "Enervate", "definition": "To sap energy from" },
    { "word": "Engender", "definition": "Give rise to" },
    { "word": "Enjoin", "definition": "Give instructions to or direct somebody to do something with authority" },
    { "word": "Enmity", "definition": "A state of deep-seated ill-will" },
    { "word": "Enormity", "definition": "An act of extreme wickedness" },
    { "word": "Enthrall", "definition": "Hold spellbound" },
    { "word": "Entice", "definition": "Get someone to do something through (often false or exaggerated) promises" },
    { "word": "Entrenched", "definition": "Fixed firmly or securely" },
    { "word": "Enumerate", "definition": "Determine the number or amount of (2) Specify individually, one by one" },
    { "word": "Ephemeral", "definition": "Lasting a very short time" },
    { "word": "Epigram", "definition": "A witty saying" },
    { "word": "Epiphany", "definition": "A sudden revelation or moment of insight" },
    { "word": "Eponym", "definition": "The name derived from a person (real or imaginary); the person for whom something is named" },
    { "word": "Equitable", "definition": "Fair to all parties as dictated by reason and conscience" },
    { "word": "Equivocal", "definition": "Confusing or ambiguous" },
    { "word": "Equivocate", "definition": "To speak vaguely, usually with the intention to mislead or deceive" },
    { "word": "Eradicate", "definition": "To completely destroy" },
    { "word": "Err", "definition": "To make an error" },
    { "word": "Errant", "definition": "To be wandering; not sticking to a circumscribed path" },
    { "word": "Erratic", "definition": "Unpredictable; strange and unconventional" },
    { "word": "Ersatz", "definition": "Not real or genuine; phony" },
    { "word": "Erudite", "definition": "Having or showing profound knowledge" },
    { "word": "Eschew", "definition": "Avoid and stay away from deliberately; stay clear of" },
    { "word": "Esoteric", "definition": "Confined to and understandable by only an enlightened inner circle" },
    { "word": "Espouse", "definition": "To adopt or support an idea or cause" },
    { "word": "Estimable", "definition": "Deserving of esteem and respect" },
    { "word": "Ethereal", "definition": "Characterized by lightness and insubstantiality" },
    { "word": "Euphoria", "definition": "A feeling of great (usually exaggerated) elation" },
    { "word": "Evanescent", "definition": "Tending to vanish like vapor" },
    { "word": "Evasive", "definition": "Avoiding or escaping from difficulty, danger, or commitment (2) Deliberately vague or ambiguous" },
    { "word": "Evenhanded", "definition": "Without partiality" },
    { "word": "Exacerbate", "definition": "Make worse" },
    { "word": "Exacting", "definition": "Requiring and demanding accuracy" },
    { "word": "Exalt", "definition": "Praise or glorify" },
    { "word": "Exasperate", "definition": "To irritate intensely" },
    { "word": "Excoriate", "definition": "To criticize very harshly" },
    { "word": "Excruciating", "definition": "Extremely painful" },
    { "word": "Execrate", "definition": "To curse and hiss at" },
    { "word": "Exegesis", "definition": "Critical explanation or analysis, especially of a text" },
    { "word": "Exemplar", "definition": "Something to be imitated" },
    { "word": "Exemplify", "definition": "Be characteristic of (2) Clarify by giving an example of" },
    { "word": "Exhort", "definition": "To strongly urge on; encourage" },
    { "word": "Exiguity", "definition": "The quality of being meager" },
    { "word": "Exonerate", "definition": "Pronounce not guilty of criminal charges" },
    { "word": "Exorbitant", "definition": "Greatly exceeding bounds of reason or moderation" },
    { "word": "Expansive", "definition": "Communicative, and prone to talking in a sociable manner" },
    { "word": "Expound", "definition": "Add details or explanation; clarify the meaning; state in depth" },
    { "word": "Expunge", "definition": "To eliminate completely" },
    { "word": "Expurgate", "definition": "To remove objectionable material" },
    { "word": "Extant", "definition": "The opposite of extinct" },
    { "word": "Extenuating", "definition": "Making less guilty or more forgivable" },
    { "word": "Extrapolate", "definition": "Draw from specific cases for more general cases" },
    { "word": "Facetious", "definition": "Cleverly amusing in tone" },
    { "word": "Facile", "definition": "Arrived at without due care or effort; lacking depth" },
    { "word": "Factious", "definition": "Produced by, or characterized by internal dissension" },
    { "word": "Factitious", "definition": "Artificial; not natural" },
    { "word": "Fallacious", "definition": "Of a belief that is based on faulty reasoning" },
    { "word": "Fastidious", "definition": "Overly concerned with details; fussy" },
    { "word": "Fawn", "definition": "Try to gain favor by extreme flattery" },
    { "word": "Feckless", "definition": "Lazy and irresponsible" },
    { "word": "Fecund", "definition": "Intellectually productive" },
    { "word": "Fell", "definition": "Terribly evil" },
    { "word": "Ferret", "definition": "To search for something persistently" },
    { "word": "Fickle", "definition": "Liable to sudden unpredictable change, esp. in affections or attachments" },
    { "word": "Finagle", "definition": "Achieve something by means of trickery or devious methods" },
    { "word": "Firebrand", "definition": "Someone who deliberately creates trouble" },
    { "word": "Flag", "definition": "Droop, sink, or settle from or as if from pressure or loss of tautness; become less intense" },
    { "word": "Fledgling", "definition": "Young and inexperienced; describing any new participant in some activity" },
    { "word": "Fleece", "definition": "To deceive" },
    { "word": "Flippant", "definition": "Showing inappropriate levity" },
    { "word": "Flounder", "definition": "Behave awkwardly; have difficulties" },
    { "word": "Flummox", "definition": "Be a mystery or bewildering to" },
    { "word": "Flush", "definition": "To be in abundance" },
    { "word": "Flux", "definition": "A state of uncertainty about what should be done" },
    { "word": "Foible", "definition": "A behavioral attribute that is distinctive and peculiar to an individual" },
    { "word": "Foment", "definition": "Try to stir up public opinion" },
    { "word": "Foolhardy", "definition": "Marked by defiant disregard for danger or consequences" },
    { "word": "Forlorn", "definition": "Marked by or showing hopelessness" },
    { "word": "Forthcoming", "definition": "Available when required or as promised (2) At ease in talking to others" },
    { "word": "Forthright", "definition": "Characterized by directness in manner or speech; without subtlety or evasion" },
    { "word": "Fortuitous", "definition": "Occurring by happy chance; having no cause or apparent cause" },
    { "word": "Fractious", "definition": "Irritable and is likely to cause disruption" },
    { "word": "Frivolous", "definition": "Not serious in content or attitude or behavior" },
    { "word": "Frugal", "definition": "Not spending much money (but spending wisely)" },
    { "word": "Frustrate", "definition": "Hinder or prevent (the efforts, plans, or desires) of" },
    { "word": "Furtive", "definition": "Marked by quiet and caution and secrecy; taking pains to avoid being observed" },
    { "word": "Futile", "definition": "Producing no result or effect; unproductive of success" },
    { "word": "Fête", "definition": "To celebrate a person" },
    { "word": "Gaffe", "definition": "A socially awkward or tactless act" },
    { "word": "Gainsay", "definition": "Deny or contradict; speak against or oppose" },
    { "word": "Gall", "definition": "The trait of being rude and impertinent (2) Feeling of deep and bitter anger and ill-will" },
    { "word": "Galvanize", "definition": "To excite or inspire (someone) to action" },
    { "word": "Gambit", "definition": "A maneuver or risk in a game or conversation, designed to secure an advantage" },
    { "word": "Garrulous", "definition": "Full of trivial conversation" },
    { "word": "Gauche", "definition": "Lacking social polish" },
    { "word": "Genial", "definition": "Agreeable, conducive to comfort" },
    { "word": "Genteel", "definition": "Marked by refinement in taste and manners" },
    { "word": "Germane", "definition": "Relevant and appropriate" },
    { "word": "Gerrymander", "definition": "To manipulate voting districts in order to favor a particular political party" },
    { "word": "Glean", "definition": "Collect information bit by bit" },
    { "word": "Glib", "definition": "(Of a person) speaking with ease but without sincerity" },
    { "word": "Glut", "definition": "An excessive supply (2) Supply with an excess of" },
    { "word": "Goad", "definition": "Urge on with unpleasant comments" },
    { "word": "Gossamer", "definition": "Characterized by unusual lightness and delicacy" },
    { "word": "Graft", "definition": "Corruption, usually through bribery" },
    { "word": "Grandiloquent", "definition": "Puffed up with vanity" },
    { "word": "Gregarious", "definition": "To be likely to socialize with others" },
    { "word": "Grovel", "definition": "Show submission or fear" },
    { "word": "Guffaw", "definition": "Laugh boisterously" },
    { "word": "Guileless", "definition": "Free of deceit" },
    { "word": "Gumption", "definition": "Resourcefulness and determination" },
    { "word": "Hackneyed", "definition": "Lacking significance through having been overused" },
    { "word": "Hagiographic", "definition": "Excessively flattering toward someone's life or work" },
    { "word": "Hail", "definition": "Enthusiastically acclaim or celebrate something" },
    { "word": "Halcyon", "definition": "Idyllically calm and peaceful; suggesting happy tranquility; marked by peace and prosperity" },
    { "word": "Hamper", "definition": "Prevent the progress or free movement of" },
    { "word": "Hamstrung", "definition": "Made ineffective or powerless" },
    { "word": "Haphazard", "definition": "Marked by great carelessness; dependent upon or characterized by chance" },
    { "word": "Harangue", "definition": "A long pompous speech; a tirade (2) To deliver a long pompous speech or tirade" },
    { "word": "Harried", "definition": "Troubled persistently especially with petty annoyances" },
    { "word": "Haughty", "definition": "Having or showing arrogant superiority to and disdain of those one views as unworthy" },
    { "word": "Hauteur", "definition": "Overbearing pride evidenced by a superior manner toward inferiors" },
    { "word": "Hector", "definition": "To bully or intimidate" },
    { "word": "Hedge", "definition": "To limit or qualify a statement; to avoid making a direct statement" },
    { "word": "Hegemony", "definition": "Dominance over a certain area" },
    { "word": "Heretic", "definition": "A person who holds unorthodox opinions in any field (not merely religion)" },
    { "word": "Heyday", "definition": "The pinnacle or top of a time period or career" },
    { "word": "Histrionic", "definition": "To be overly theatrical" },
    { "word": "Hoary", "definition": "Ancient" },
    { "word": "Hobble", "definition": "To hold back the progress of something" },
    { "word": "Hodgepodge", "definition": "A confusing mixture or jumble" },
    { "word": "Hoodwink", "definition": "To deceive or trick someone" },
    { "word": "Hound", "definition": "To pursue relentlessly" },
    { "word": "Hubris", "definition": "Overbearing pride or presumption" },
    { "word": "Humdrum", "definition": "Dull and lacking excitement" },
    { "word": "Iconoclast", "definition": "Somebody who attacks cherished beliefs or institutions" },
    { "word": "Iconoclastic", "definition": "Defying tradition or convention" },
    { "word": "Idiosyncrasy", "definition": "A behavioral attribute that is distinctive and peculiar to an individual" },
    { "word": "Ignoble", "definition": "Dishonorable" },
    { "word": "Ignominious", "definition": "Deserving or bringing disgrace or shame" },
    { "word": "Illicit", "definition": "Contrary to or forbidden by law" },
    { "word": "Illustrious", "definition": "Widely known and esteemed; having or conferring glory" },
    { "word": "Imbibe", "definition": "To drink or absorb as if drinking" },
    { "word": "Imbroglio", "definition": "A confusing and potentially embarrassing situation" },
    { "word": "Immaterial", "definition": "Not relevant" },
    { "word": "Immure", "definition": "To enclose, usually in walls" },
    { "word": "Immutable", "definition": "Not able to be changed" },
    { "word": "Impartial", "definition": "Free from undue bias or preconceived opinions" },
    { "word": "Impeccable", "definition": "Without fault or error" },
    { "word": "Impecunious", "definition": "Lacking money; poor" },
    { "word": "Impede", "definition": "Be a hindrance or obstacle to" },
    { "word": "Impending", "definition": "Close in time; about to occur" },
    { "word": "Imperious", "definition": "Having or showing arrogant superiority to and disdain of those one views as unworthy" },
    { "word": "Impermeable", "definition": "Does not allow fluids to pass through" },
    { "word": "Impertinent", "definition": "Being disrespectful; improperly forward or bold" },
    { "word": "Impervious", "definition": "Not admitting of passage or capable of being affected" },
    { "word": "Impetuous", "definition": "Characterized by undue haste and lack of thought or deliberation" },
    { "word": "Implacable", "definition": "Incapable of making less angry or hostile" },
    { "word": "Implausible", "definition": "Describing a statement that is not believable" },
    { "word": "Implicate", "definition": "Convey a meaning; imply (2) To indicate in wrongdoing, usually a crime" },
    { "word": "Imponderable", "definition": "Impossible to estimate or figure out" },
    { "word": "Importuned", "definition": "Beg persistently and urgently" },
    { "word": "Impregnable", "definition": "Immune to attack; incapable of being tampered with" },
    { "word": "Improvident", "definition": "Not given careful consideration" },
    { "word": "Imprudent", "definition": "Not wise" },
    { "word": "Impudent", "definition": "Improperly forward or bold" },
    { "word": "Impugn", "definition": "Attack as false or wrong" },
    { "word": "Impute", "definition": "Attribute (responsibility or fault) to something" },
    { "word": "Inadvertent", "definition": "Happening by chance or unexpectedly or unintentionally" },
    { "word": "Inanity", "definition": "Total lack of meaning or ideas" },
    { "word": "Inarticulate", "definition": "Without or deprived of the use of speech or words" },
    { "word": "Incense", "definition": "Make furious" },
    { "word": "Incessant", "definition": "Uninterrupted in time and indefinitely long continuing" },
    { "word": "Inchoate", "definition": "Only partly in existence; imperfectly formed" },
    { "word": "Incisive", "definition": "Having or demonstrating ability to recognize or draw fine distinctions" },
    { "word": "Inclement", "definition": "(Of weather) unpleasant, stormy" },
    { "word": "Incongruous", "definition": "Lacking in harmony or compatibility or appropriateness" },
    { "word": "Incontrovertible", "definition": "Necessarily or demonstrably true; impossible to deny or disprove" },
    { "word": "Incorrigible", "definition": "Impervious to correction by punishment" },
    { "word": "Incumbent", "definition": "Necessary (for someone) as a duty or responsibility" },
    { "word": "Indecorous", "definition": "Not in keeping with accepted standards of what is right or proper in polite society" },
    { "word": "Indict", "definition": "To formally charge or accuse of wrongdoing" },
    { "word": "Indifference", "definition": "The trait of seeming not to care" },
    { "word": "Indigenous", "definition": "Originating in a certain area" },
    { "word": "Indigent", "definition": "Poor; having very little (2) A poor or needy person" },
    { "word": "Indignant", "definition": "Feeling anger over a perceived injustice" },
    { "word": "Industrious", "definition": "Characterized by hard work and perseverance" },
    { "word": "Ineffable", "definition": "Too sacred to be uttered; defying expression or description" },
    { "word": "Ineluctable", "definition": "Impossible to avoid or evade" },
    { "word": "Inequity", "definition": "Injustice by virtue of not conforming with rules or standards" },
    { "word": "Inexorable", "definition": "Impossible to stop or prevent" },
    { "word": "Infelicitous", "definition": "Inappropriate" },
    { "word": "Inflammable", "definition": "Extremely controversial, incendiary" },
    { "word": "Ingenuity", "definition": "The power of creative imagination" },
    { "word": "Ingenuous", "definition": "To be naive and innocent" },
    { "word": "Ingratiate", "definition": "Gain favor with somebody by deliberate efforts" },
    { "word": "Inimical", "definition": "Hostile (usually describes conditions or environments)" },
    { "word": "Inimitable", "definition": "Defying imitation; matchless" },
    { "word": "Inkling", "definition": "A slight suggestion or vague understanding" },
    { "word": "Innocuous", "definition": "Harmless and doesn't produce any ill effects" },
    { "word": "Inscrutable", "definition": "Not easily understood; unfathomable" },
    { "word": "Insidious", "definition": "Working in a subtle but destructive way" },
    { "word": "Insipid", "definition": "Dull and uninteresting" },
    { "word": "Insolent", "definition": "Rude and arrogant" },
    { "word": "Insolvent", "definition": "Unable to pay one's bills; bankrupt" },
    { "word": "Insouciance", "definition": "Lack of concern" },
    { "word": "Insufferable", "definition": "Intolerable, difficult to endure" },
    { "word": "Internecine", "definition": "Of conflict within a group or organization" },
    { "word": "Intimate", "definition": "To suggest something subtly" },
    { "word": "Intimation", "definition": "An indirect suggestion" },
    { "word": "Intransigent", "definition": "Unwilling to change one's beliefs or course of action" },
    { "word": "Intrepid", "definition": "Fearless" },
    { "word": "Inure", "definition": "To make accustomed to something unpleasant" },
    { "word": "Invective", "definition": "Abusive or denunciatory language" },
    { "word": "Inveterate", "definition": "Habitual" },
    { "word": "Invidious", "definition": "Likely to cause resentment" },
    { "word": "Inviolable", "definition": "Never to be broken, infringed, or dishonored" },
    { "word": "Inviolate", "definition": "Must be kept sacred" },
    { "word": "Involved", "definition": "Complicated and difficult to comprehend" },
    { "word": "Irrefutable", "definition": "Impossible to deny or disprove" },
    { "word": "Irresolute", "definition": "Uncertain how to act or proceed" },
    { "word": "Irrevocable", "definition": "Incapable of being retracted or revoked" },
    { "word": "Itinerant", "definition": "Traveling from place to place to work" },
    { "word": "Jargon", "definition": "A characteristic language of a particular group" },
    { "word": "Jaundice", "definition": "To be biased against due to envy or prejudice" },
    { "word": "Jejune", "definition": "Dull; lacking flavor (2) Immature; childish" },
    { "word": "Jingoism", "definition": "Fanatical patriotism" },
    { "word": "Jingoist", "definition": "A person who thinks that their country should be at war" },
    { "word": "Jocular", "definition": "Characterized by jokes and good humor" },
    { "word": "Jovial", "definition": "Full of or showing high-spirited merriment" },
    { "word": "Jubilant", "definition": "Full of high-spirited delight because of triumph or success" },
    { "word": "Juggernaut", "definition": "A force that cannot be stopped" },
    { "word": "Junta", "definition": "An aggressive takeover by a group (usually military)" },
    { "word": "Juxtapose", "definition": "Place side by side" },
    { "word": "Kowtow", "definition": "To bow or act in a subservient manner" },
    { "word": "Laborious", "definition": "Characterized by effort to the point of exhaustion; especially physical effort" },
    { "word": "Lacerate", "definition": "Deeply hurt the feelings of; distress" },
    { "word": "Lachrymose", "definition": "Showing sorrow" },
    { "word": "Laconic", "definition": "One who says very few words" },
    { "word": "Lambast", "definition": "Criticize severely or angrily" },
    { "word": "Lampoon", "definition": "Ridicule with satire" },
    { "word": "Languid", "definition": "Not inclined towards physical exertion or effort; slow and relaxed" },
    { "word": "Languish", "definition": "Become feeble" },
    { "word": "Largess", "definition": "Extreme generosity and giving" },
    { "word": "Lascivious", "definition": "Lecherous; sexually perverted" },
    { "word": "Laudable", "definition": "Worthy of high praise" },
    { "word": "Leery", "definition": "Openly distrustful and unwilling to confide" },
    { "word": "Lethargic", "definition": "Lacking energy" },
    { "word": "Limpid", "definition": "Clarity in terms of expression" },
    { "word": "Lionize", "definition": "Assign great social importance to" },
    { "word": "Litany", "definition": "Any long and tedious account of something" },
    { "word": "Loath", "definition": "Unwillingness to do something contrary to your custom (usually followed by 'to')" },
    { "word": "Lucid", "definition": "(Of language) transparently clear; easily understandable" },
    { "word": "Lugubrious", "definition": "Excessively mournful" },
    { "word": "Macabre", "definition": "Suggesting the horror of death and decay; gruesome" },
    { "word": "Machinate", "definition": "Engage in plotting or enter into a conspiracy, swear together" },
    { "word": "Magisterial", "definition": "Offensively self-assured or given to exercising unwarranted power" },
    { "word": "Magnanimous", "definition": "Noble and generous in spirit, especially towards a rival or someone less powerful" },
    { "word": "Maintain", "definition": "To assert" },
    { "word": "Maladroit", "definition": "Clumsy" },
    { "word": "Malady", "definition": "A disease or sickness" },
    { "word": "Malapropism", "definition": "The confusion of a word with another word that sounds similar" },
    { "word": "Malevolent", "definition": "Wishing or appearing to wish evil to others; arising from intense ill will or hatred" },
    { "word": "Malfeasance", "definition": "Misconduct or wrongdoing (especially by a public official)" },
    { "word": "Malingerer", "definition": "Someone shirking their duty by pretending to be sick or incapacitated" },
    { "word": "Malleable", "definition": "Capable of being shaped or bent or drawn out (2) Easily influenced" },
    { "word": "Malodorous", "definition": "Having an unpleasant smell" },
    { "word": "Martial", "definition": "Suggesting war or military life" },
    { "word": "Martinet", "definition": "A strict disciplinarian" },
    { "word": "Maudlin", "definition": "Overly emotional and sad" },
    { "word": "Maunder", "definition": "Wander aimlessly (2) Speak (about unimportant matters) rapidly and incessantly" },
    { "word": "Maverick", "definition": "Someone who exhibits great independence in thought and action" },
    { "word": "Mawkish", "definition": "Overly sentimental to the point that it is disgusting" },
    { "word": "Maxim", "definition": "A short saying expressing a general truth" },
    { "word": "Meander", "definition": "To wander aimlessly" },
    { "word": "Melancholy", "definition": "A deep, long-lasting sadness" },
    { "word": "Melee", "definition": "A wild, confusing fight or struggle" },
    { "word": "Mellifluous", "definition": "Smooth and sweet-sounding" },
    { "word": "Mendacity", "definition": "The tendency to be untruthful" },
    { "word": "Mendicant", "definition": "A pauper who lives by begging" },
    { "word": "Mercurial", "definition": "Prone to unexpected and unpredictable changes in mood" },
    { "word": "Mesmerize", "definition": "To spellbind or enthrall" },
    { "word": "Meteoric", "definition": "Like a meteor in speed or brilliance or transience" },
    { "word": "Meticulous", "definition": "Marked by extreme care in treatment of details" },
    { "word": "Mettlesome", "definition": "Filled with courage or valor" },
    { "word": "Misanthrope", "definition": "A hater of mankind" },
    { "word": "Misattribute", "definition": "To erroneously attribute; to falsely ascribe" },
    { "word": "Misconstrue", "definition": "Interpret in the wrong way" },
    { "word": "Miscreant", "definition": "A person who breaks the law" },
    { "word": "Miser", "definition": "A person who doesn't like to spend money (because they are greedy)" },
    { "word": "Misogynist", "definition": "A person who dislikes women in particular" },
    { "word": "Mitigate", "definition": "Make less severe or harsh (2) Lessen the severity of an offense" },
    { "word": "Modicum", "definition": "A small or moderate or token amount" },
    { "word": "Mollify", "definition": "To make someone less angry; placate" },
    { "word": "Moment", "definition": "Significant and important value" },
    { "word": "Moot", "definition": "Open to argument or debate; undecidable in a meaningless or irrelevant way" },
    { "word": "Mordant", "definition": "Biting and caustic in thought, manner, or style" },
    { "word": "Moribund", "definition": "Being on the point of death; declining rapidly losing all momentum in progress" },
    { "word": "Morose", "definition": "Ill-tempered and not inclined to talk; gloomy" },
    { "word": "Morph", "definition": "To undergo dramatic change in a seamless and barely noticeable fashion" },
    { "word": "Mulct", "definition": "To defraud or swindle" },
    { "word": "Mundane", "definition": "Repetitive and boring; not spiritual (2) Relating to the ordinary world" },
    { "word": "Munificent", "definition": "Very generous" },
    { "word": "Muted", "definition": "Softened, subdued" },
    { "word": "Myopic", "definition": "Lacking foresight or imagination" },
    { "word": "Myriad", "definition": "A large indefinite number" },
    { "word": "Nadir", "definition": "The lowest point" },
    { "word": "Negligible", "definition": "So small as to be meaningless; insignificant" },
    { "word": "Nettlesome", "definition": "Causing irritation or annoyance" },
    { "word": "Noisome", "definition": "Having an extremely bad smell" },
    { "word": "Nonchalant", "definition": "Coming across as coolly uninterested" },
    { "word": "Nonplussed", "definition": "Unsure how to act or respond" },
    { "word": "Nuance", "definition": "A subtle difference in meaning or opinion or attitude" },
    { "word": "Obdurate", "definition": "Stubbornly persistent in changing an opinion or action" },
    { "word": "Objurgate", "definition": "Express strong disapproval of" },
    { "word": "Obliging", "definition": "Showing a cheerful willingness to do favors for others" },
    { "word": "Oblique", "definition": "Not straightforward; indirect" },
    { "word": "Obscure", "definition": "Make unclear (2) Known by only a few" },
    { "word": "Obsequious", "definition": "Attentive in an ingratiating or servile manner; attempting to win favor from influential people by flattery" },
    { "word": "Obstinate", "definition": "Resistant to guidance or discipline; stubbornly persistent" },
    { "word": "Obstreperous", "definition": "Noisily and stubbornly defiant; willfully difficult to control" },
    { "word": "Obtain", "definition": "Be valid, applicable, or true" },
    { "word": "Obtuse", "definition": "Slow to learn or understand; lacking intellectual acuity" },
    { "word": "Officious", "definition": "Intrusive in a meddling or offensive manner" },
    { "word": "Opaque", "definition": "Not clearly understood or expressed" },
    { "word": "Opulence", "definition": "Wealth as evidenced by sumptuous living" },
    { "word": "Ornate", "definition": "Marked by elaborate rhetoric and elaborated with decorative details" },
    { "word": "Ossify", "definition": "Make rigid and set into a conventional pattern" },
    { "word": "Ostentatious", "definition": "Intended to attract notice and impress others; tawdry or vulgar" },
    { "word": "Ostracize", "definition": "Exclude from a community or group" },
    { "word": "Overweening", "definition": "Arrogant; presumptuous" },
    { "word": "Palatable", "definition": "Acceptable to the taste or mind" },
    { "word": "Palaver", "definition": "Speak (about unimportant matters) rapidly and incessantly" },
    { "word": "Palimpsest", "definition": "Something that has been changed numerous times but on which traces of former iterations can still be seen" },
    { "word": "Panacea", "definition": "Hypothetical remedy for all ills or diseases; a universal solution" },
    { "word": "Panache", "definition": "Distinctive and stylish elegance" },
    { "word": "Panegyric", "definition": "A formal expression of praise" },
    { "word": "Paradoxical", "definition": "Seemingly contradictory but nonetheless possibly true" },
    { "word": "Paragon", "definition": "Model of excellence or perfection of a kind; one having no equal" },
    { "word": "Pariah", "definition": "An outcast" },
    { "word": "Parochial", "definition": "Narrowly restricted in scope or outlook" },
    { "word": "Parsimonious", "definition": "Extremely frugal; miserly" },
    { "word": "Parvenu", "definition": "A person who has suddenly become wealthy, but not socially accepted as part of a higher class" },
    { "word": "Pastoral", "definition": "Relating to the countryside in a pleasant sense" },
    { "word": "Patent", "definition": "Glaringly obvious" },
    { "word": "Patronize", "definition": "To treat condescendingly" },
    { "word": "Paucity", "definition": "A lack of something" },
    { "word": "Pecuniary", "definition": "Relating to or involving money" },
    { "word": "Pedantic", "definition": "Marked by a narrow focus on or display of learning especially its trivial aspects" },
    { "word": "Pedestrian", "definition": "Lacking imagination" },
    { "word": "Peevish", "definition": "Easily irritated or annoyed" },
    { "word": "Pejorative", "definition": "Expressing disapproval (usually refers to a term)" },
    { "word": "Pellucid", "definition": "Transparently clear; easily understandable" },
    { "word": "Penurious", "definition": "Lacking money; poor (2) Miserly" },
    { "word": "Percipient", "definition": "Highly perceptive" },
    { "word": "Peremptory", "definition": "Bossy and domineering" },
    { "word": "Perennial", "definition": "Lasting an indefinitely long time; eternal; everlasting" },
    { "word": "Perfidy", "definition": "An act of deliberate betrayal; a breach of a trust" },
    { "word": "Perfunctory", "definition": "Done routinely and with little interest or care" },
    { "word": "Peripatetic", "definition": "Traveling by foot" },
    { "word": "Pernicious", "definition": "Exceedingly harmful; working or spreading in a hidden and injurious way" },
    { "word": "Perpetuate", "definition": "Cause to continue" },
    { "word": "Perquisite", "definition": "A right reserved exclusively by a particular person or group (especially a hereditary or official right)" },
    { "word": "Perspicacious", "definition": "Acutely insightful and wise" },
    { "word": "Pertinent", "definition": "Having precise or logical relevance to the matter at hand" },
    { "word": "Perturb", "definition": "Disturb in mind or cause to be worried or alarmed" },
    { "word": "Peruse", "definition": "To read very carefully" },
    { "word": "Petulant", "definition": "Easily irritated or annoyed" },
    { "word": "Phantasmagorical", "definition": "Illusive; unreal" },
    { "word": "Philistine", "definition": "Smug and ignorant towards artistic and cultural values" },
    { "word": "Phlegmatic", "definition": "Showing little emotion" },
    { "word": "Picayune", "definition": "Trifling or petty (a person)" },
    { "word": "Pillory", "definition": "Ridicule or expose to public scorn" },
    { "word": "Pine", "definition": "To yearn for" },
    { "word": "Pinnacle", "definition": "The highest point" },
    { "word": "Piquant", "definition": "Having an agreeably pungent taste" },
    { "word": "Pith", "definition": "The most essential part of something" },
    { "word": "Pithy", "definition": "Concise and full of meaning" },
    { "word": "Pittance", "definition": "A small amount (of money)" },
    { "word": "Placate", "definition": "Cause to be more favorably inclined; gain the goodwill of" },
    { "word": "Placid", "definition": "Not easily irritated" },
    { "word": "Platitude", "definition": "A trite or obvious remark" },
    { "word": "Plodding", "definition": "(Of movement) slow and laborious" },
    { "word": "Ploy", "definition": "A clever plan to turn a situation to one's advantage" },
    { "word": "Plucky", "definition": "Marked by courage and determination" },
    { "word": "Poignant", "definition": "Emotionally touching" },
    { "word": "Polemic", "definition": "A strong verbal or written attack on someone or something" },
    { "word": "Pollyannaish", "definition": "Extremely optimistic" },
    { "word": "Ponderous", "definition": "Weighed-down; moving slowly" },
    { "word": "Pontificate", "definition": "Talk in a dogmatic and pompous manner" },
    { "word": "Portentous", "definition": "Ominously prophetic" },
    { "word": "Posit", "definition": "Assume as fact" },
    { "word": "Powwow", "definition": "An informal meeting or discussion" },
    { "word": "Pragmatic", "definition": "Guided by practical experience and observation rather than theory" },
    { "word": "Precarious", "definition": "Fraught with danger" },
    { "word": "Precedent", "definition": "An example that is used to justify similar occurrences at a later time" },
    { "word": "Precipitate", "definition": "Hasty or rash (2) To cause to happen" },
    { "word": "Precipitous", "definition": "Done with very great haste and without due deliberation" },
    { "word": "Preclude", "definition": "Keep from happening or arising; make impossible" },
    { "word": "Precocious", "definition": "Characterized by exceptionally early development or maturity (especially in mental aptitude)" },
    { "word": "Predilection", "definition": "A strong liking" },
    { "word": "Preempt", "definition": "To take the place of or have precedence over" },
    { "word": "Preemptive", "definition": "Done before someone else can do it" },
    { "word": "Prescience", "definition": "The power to foresee the future" },
    { "word": "Presentiment", "definition": "A feeling of evil to come" },
    { "word": "Presumption", "definition": "An assumption that is taken for granted (2) Audacious (even arrogant) behavior that you have no right to" },
    { "word": "Presumptuous", "definition": "Excessively forward" },
    { "word": "Prevail", "definition": "Be widespread in a particular area at a particular time; be current" },
    { "word": "Prevaricate", "definition": "To speak in an evasive way" },
    { "word": "Primacy", "definition": "The state of being first in importance" },
    { "word": "Pristine", "definition": "Unspoiled, untouched (usually of nature)" },
    { "word": "Probity", "definition": "Integrity, strong moral principles" },
    { "word": "Prodigal", "definition": "Rashly or wastefully extravagant" },
    { "word": "Prodigious", "definition": "So great in size or force or extent as to elicit awe" },
    { "word": "Profligate", "definition": "Spending money recklessly or wastefully" },
    { "word": "Profuse", "definition": "Plentiful; pouring out in abundance" },
    { "word": "Prognostication", "definition": "A statement made about the future" },
    { "word": "Prolific", "definition": "Intellectually productive" },
    { "word": "Prolixity", "definition": "Boring verbosity" },
    { "word": "Promulgate", "definition": "State or announce" },
    { "word": "Propitiate", "definition": "To placate or appease" },
    { "word": "Propitious", "definition": "Presenting favorable circumstances; likely to result in or show signs of success" },
    { "word": "Proponent", "definition": "A person who pleads for a cause or propounds an idea" },
    { "word": "Prosaic", "definition": "Dull and lacking imagination" },
    { "word": "Proscribe", "definition": "Command against" },
    { "word": "Proselytize", "definition": "Convert to another religion, philosophy, or perspective" },
    { "word": "Protean", "definition": "Readily taking on different roles; versatile" },
    { "word": "Provident", "definition": "Careful in regard to your own interests; providing carefully for the future" },
    { "word": "Provincial", "definition": "Characteristic of a limited perspective; not fashionable or sophisticated" },
    { "word": "Provisional", "definition": "Under terms not final or fully worked out or agreed upon" },
    { "word": "Puerile", "definition": "Of or characteristic of a child; displaying or suggesting a lack of maturity" },
    { "word": "Pugnacious", "definition": "Eager to fight or argue; verbally combative" },
    { "word": "Puissant", "definition": "Powerful" },
    { "word": "Punctilious", "definition": "Marked by precise accordance with details" },
    { "word": "Pundit", "definition": "Someone who has been admitted to membership in a scholarly field" },
    { "word": "Pyrrhic", "definition": "Describing a victory that comes at such a great cost that the victory is not worthwhile" },
    { "word": "Quail", "definition": "Draw back, as with fear or pain" },
    { "word": "Qualify", "definition": "To be legally competent or capable (2) To make less severe; to limit (a statement)" },
    { "word": "Qualm", "definition": "Uneasiness about the fitness of an action" },
    { "word": "Quandary", "definition": "A state of uncertainty or perplexity especially as requiring a choice between equally unfavorable options" },
    { "word": "Querulous", "definition": "Habitually complaining" },
    { "word": "Quip", "definition": "A witty saying or remark" },
    { "word": "Quisling", "definition": "A traitor" },
    { "word": "Quixotic", "definition": "Wildly idealistic; impractical" },
    { "word": "Quotidian", "definition": "Found in the ordinary course of events" },
    { "word": "Raconteur", "definition": "A person skilled in telling anecdotes" },
    { "word": "Raffish", "definition": "Marked by a carefree unconventionality or disreputableness" },
    { "word": "Raft", "definition": "A large number of something" },
    { "word": "Raillery", "definition": "Light teasing" },
    { "word": "Rakish", "definition": "Marked by a carefree unconventionality or disreputableness" },
    { "word": "Rankle", "definition": "Gnaw into; make resentful or angry" },
    { "word": "Rapprochement", "definition": "The reestablishing of cordial relations" },
    { "word": "Rarefied", "definition": "Make more subtle or refined" },
    { "word": "Rash", "definition": "Marked by defiant disregard for danger or consequences; imprudently incurring risk" },
    { "word": "Ravenous", "definition": "Extremely hungry; devouring or craving food in great quantities" },
    { "word": "Rebuke", "definition": "Criticize severely or angrily; censure" },
    { "word": "Recapitulation", "definition": "A summary (think of recap)" },
    { "word": "Reconcile", "definition": "Make (one thing) compatible with (another)" },
    { "word": "Recondite", "definition": "Difficult to penetrate; incomprehensible to one of ordinary understanding or knowledge" },
    { "word": "Recrimination", "definition": "Mutual accusations" },
    { "word": "Recrudesce", "definition": "To break out or happen again" },
    { "word": "Redoubtable", "definition": "Inspiring fear or awe" },
    { "word": "Redress", "definition": "An act of making something right" },
    { "word": "Refractory", "definition": "Stubbornly resistant to authority or control" },
    { "word": "Refute", "definition": "Prove to be false or incorrect" },
    { "word": "Relegate", "definition": "Assign to a lower position" },
    { "word": "Remiss", "definition": "To be negligent in one's duty" },
    { "word": "Remonstrate", "definition": "To make objections while pleading" },
    { "word": "Renege", "definition": "Fail to fulfill a promise or obligation" },
    { "word": "Replete", "definition": "Completely stocked or furnished with something" },
    { "word": "Reprisal", "definition": "A retaliatory action against an enemy in wartime" },
    { "word": "Reproach", "definition": "To express criticism towards" },
    { "word": "Repudiate", "definition": "Reject as untrue or unfounded" },
    { "word": "Rescind", "definition": "Cancel officially" },
    { "word": "Reservation", "definition": "An unstated doubt that prevents you from accepting something wholeheartedly" },
    { "word": "Resignation", "definition": "The acceptance of something unpleasant that can't be avoided" },
    { "word": "Resolve", "definition": "Reach a conclusion after a discussion or deliberation" },
    { "word": "Respite", "definition": "A pause from doing something (as work)" },
    { "word": "Restive", "definition": "Restless" },
    { "word": "Resurgent", "definition": "Rising again as to new life and vigor" },
    { "word": "Reticent", "definition": "Reluctant to draw attention to yourself; temperamentally disinclined to talk" },
    { "word": "Retiring", "definition": "To be shy, and to be inclined to retract from company" },
    { "word": "Retract", "definition": "Pull inward or towards a center; formally reject or disavow a formerly held belief, usually under pressure" },
    { "word": "Reverent", "definition": "Feeling or showing profound respect or veneration" },
    { "word": "Ribald", "definition": "Humorously vulgar" },
    { "word": "Rile", "definition": "Cause annoyance in; disturb, especially by minor irritations" },
    { "word": "Robust", "definition": "Sturdy and strong in form, constitution, or construction" },
    { "word": "Row", "definition": "An angry dispute" },
    { "word": "Rudimentary", "definition": "Being in the earliest stages of development; being or involving basic facts or principles" },
    { "word": "Rustic", "definition": "Characteristic of rural life; awkwardly simple and provincial" },
    { "word": "Sagacious", "definition": "Having good judgment and acute insight" },
    { "word": "Sanctimonious", "definition": "Making a show of being pious; holier-than-thou" },
    { "word": "Sanction", "definition": "Give authority or permission to (2) A legal penalty for a forbidden action" },
    { "word": "Sangfroid", "definition": "Calmness or poise in difficult situations" },
    { "word": "Sanguine", "definition": "Cheerful; optimistic" },
    { "word": "Sardonic", "definition": "Disdainfully or ironically humorous; scornful and mocking" },
    { "word": "Sartorial", "definition": "Related to fashion or clothes" },
    { "word": "Saturnine", "definition": "Morose or gloomy" },
    { "word": "Savvy", "definition": "A perceptive understanding" },
    { "word": "Schadenfreude", "definition": "Joy from watching the suffering of others" },
    { "word": "Scintillating", "definition": "Describes someone who is brilliant and lively" },
    { "word": "Screed", "definition": "An abusive rant (often tedious)" },
    { "word": "Scrupulous", "definition": "Characterized by extreme care and great effort (2) Having a sense of right and wrong; principled" },
    { "word": "Sedulous", "definition": "Done diligently and carefully" },
    { "word": "Self-effacing", "definition": "Reluctant to draw attention to yourself" },
    { "word": "Semblance", "definition": "An outward or token appearance or form that is deliberately misleading" },
    { "word": "Sententious", "definition": "To be moralizing, usually in a pompous sense" },
    { "word": "Sentimental", "definition": "Effusively or insincerely emotional, especially in art, music, and literature" },
    { "word": "Serendipity", "definition": "The instance in which an accidental, fortunate discovery is made" },
    { "word": "Serene", "definition": "Calm and peaceful" },
    { "word": "Simulacrum", "definition": "A representation of a person (especially in the form of sculpture) (2) A bad imitation" },
    { "word": "Sinecure", "definition": "An office that involves minimal duties" },
    { "word": "Slapdash", "definition": "Carelessly and hastily put together" },
    { "word": "Smattering", "definition": "A slight or superficial understanding of a subject; a small amount of something" },
    { "word": "Smug", "definition": "Marked by excessive complacency or self-satisfaction" },
    { "word": "Snide", "definition": "Expressive of contempt; derogatory or mocking in an indirect way" },
    { "word": "Snub", "definition": "Refuse to acknowledge; reject outright and bluntly" },
    { "word": "Solecism", "definition": "A socially awkward or tactless act" },
    { "word": "Solicitous", "definition": "Showing hovering attentiveness" },
    { "word": "Solicitude", "definition": "A feeling of excessive concern" },
    { "word": "Soporific", "definition": "Inducing mental lethargy; sleep-inducing" },
    { "word": "Sordid", "definition": "Involving ignoble actions and motives; arousing moral distaste and contempt" },
    { "word": "Spartan", "definition": "Unsparing and uncompromising in discipline or judgment; practicing great self-denial" },
    { "word": "Specious", "definition": "Based on pretense; deceptively pleasing (2) Plausible but false" },
    { "word": "Spendthrift", "definition": "One who spends money extravagantly" },
    { "word": "Splenetic", "definition": "Very irritable" },
    { "word": "Sporadic", "definition": "Recurring in scattered and irregular or unpredictable instances" },
    { "word": "Spurious", "definition": "Plausible but false" },
    { "word": "Spurn", "definition": "Reject with contempt" },
    { "word": "Squander", "definition": "Spend thoughtlessly; waste time, money, or an opportunity" },
    { "word": "Squelch", "definition": "Suppress or crush completely" },
    { "word": "Staid", "definition": "Characterized by dignity and propriety" },
    { "word": "Stalwart", "definition": "Dependable; inured to fatigue or hardships" },
    { "word": "Start", "definition": "To suddenly move in a particular direction" },
    { "word": "Staunch", "definition": "Firm and dependable especially in loyalty" },
    { "word": "Steadfast", "definition": "Marked by firm determination or resolution; not shakable" },
    { "word": "Stem", "definition": "To hold back or limit the flow or growth of something" },
    { "word": "Stipend", "definition": "A regular allowance (of money)" },
    { "word": "Stolid", "definition": "Having or revealing little emotion or sensibility; not easily aroused or excited" },
    { "word": "Stringent", "definition": "Demanding strict attention to rules and procedures" },
    { "word": "Stultify", "definition": "Cause one, through routine, to lose energy and enthusiasm" },
    { "word": "Stymie", "definition": "Hinder or prevent the progress or accomplishment of" },
    { "word": "Subsume", "definition": "Contain or include" },
    { "word": "Subterfuge", "definition": "Something intended to misrepresent the true nature of an activity" },
    { "word": "Subversive", "definition": "In opposition to a civil authority or government" },
    { "word": "Sullen", "definition": "Showing a brooding ill humor" },
    { "word": "Summit", "definition": "The peak or highest point" },
    { "word": "Supercilious", "definition": "Haughty and disdainful; looking down on others" },
    { "word": "Superfluous", "definition": "Serving no useful purpose" },
    { "word": "Supplant", "definition": "Take the place or move into the position of" },
    { "word": "Surfeit", "definition": "An excessive amount of something" },
    { "word": "Surly", "definition": "Inclined to anger or bad feelings with overtones of menace" },
    { "word": "Surreptitious", "definition": "Stealthy, taking pains not to be caught or detected" },
    { "word": "Sybarite", "definition": "A person who indulges in luxury" },
    { "word": "Sycophant", "definition": "A person who tries to please someone in order to gain a personal advantage" },
    { "word": "Taciturn", "definition": "Habitually reserved and uncommunicative" },
    { "word": "Tact", "definition": "Consideration in dealing with others and avoiding giving offense" },
    { "word": "Tantamount", "definition": "Being essentially equal to something" },
    { "word": "Tarnish", "definition": "Make dirty or spotty, as by exposure to air; also used metaphorically" },
    { "word": "Tawdry", "definition": "Tastelessly showy; cheap and shoddy" },
    { "word": "Taxing", "definition": "Use to the limit; exhaust" },
    { "word": "Telling", "definition": "Significant and revealing of another factor" },
    { "word": "Telltale", "definition": "Revealing" },
    { "word": "Temerity", "definition": "Fearless daring" },
    { "word": "Temperance", "definition": "The trait of avoiding excesses" },
    { "word": "Tempestuous", "definition": "As if driven by turbulent or conflicting emotions; highly energetic and wildly changing or fluctuating" },
    { "word": "Tenacious", "definition": "Stubbornly unyielding" },
    { "word": "Tendentious", "definition": "Likely to lean towards a controversial view" },
    { "word": "Tender", "definition": "Offer up something formally" },
    { "word": "Thoroughgoing", "definition": "Very thorough; complete" },
    { "word": "Thrifty", "definition": "Spending money wisely" },
    { "word": "Thwart", "definition": "Hinder or prevent (the efforts, plans, or desires) of" },
    { "word": "Timorous", "definition": "Timid by nature or revealing fear and nervousness" },
    { "word": "Tirade", "definition": "An angry speech" },
    { "word": "Torpor", "definition": "Inactivity resulting from lethargy and lack of vigor or energy" },
    { "word": "Tout", "definition": "Advertise in strongly positive terms; show off" },
    { "word": "Transitory", "definition": "Lasting a very short time" },
    { "word": "Transmute", "definition": "Change or alter in form, appearance, or nature" },
    { "word": "Travail", "definition": "Use of physical or mental energy; hard work; agony or anguish" },
    { "word": "Trenchant", "definition": "Characterized by or full of force and vigor; having keenness and forcefulness and penetration in thought, expression, or intellect" },
    { "word": "Tribulation", "definition": "Something, especially an event, that causes difficulty and suffering" },
    { "word": "Trite", "definition": "Repeated too often; overfamiliar through overuse" },
    { "word": "Truculence", "definition": "Defiant aggressiveness" },
    { "word": "Truculent", "definition": "Having a fierce, savage nature" },
    { "word": "Truncate", "definition": "Reduce the length of something" },
    { "word": "Tumult", "definition": "A state of chaos, noise, and confusion" },
    { "word": "Turgid", "definition": "Pompous and tedious" },
    { "word": "Turpitude", "definition": "Depravity; a depraved act" },
    { "word": "Tyro", "definition": "Someone new to a field or activity" },
    { "word": "Umbrage", "definition": "A feeling of anger caused by being offended" },
    { "word": "Unassailable", "definition": "Immune to attack; without flaws" },
    { "word": "Uncanny", "definition": "Suggesting the operation of supernatural influences; surpassing the ordinary or normal" },
    { "word": "Uncompromising", "definition": "Not making concessions" },
    { "word": "Unconscionable", "definition": "Unreasonable; unscrupulous; excessive" },
    { "word": "Undermine", "definition": "To weaken (usually paired with an abstract term)" },
    { "word": "Underscore", "definition": "Give extra weight to (a communication)" },
    { "word": "Underwrite", "definition": "To support financially" },
    { "word": "Unequivocal", "definition": "Admitting of no doubt or misunderstanding; having only one meaning or interpretation and leading to only one conclusion" },
    { "word": "Unflappable", "definition": "Not easily perturbed or excited or upset; marked by extreme calm and composure" },
    { "word": "Unforthcoming", "definition": "Uncooperative, not willing to give up information" },
    { "word": "Unimpeachable", "definition": "Free of guilt; not subject to blame; beyond doubt or reproach" },
    { "word": "Unnerve", "definition": "To make nervous or upset" },
    { "word": "Unprecedented", "definition": "Having never been done or known before; novel" },
    { "word": "Unprepossessing", "definition": "Creating an unfavorable or neutral first impression" },
    { "word": "Unpropitious", "definition": "With little chance of success" },
    { "word": "Unruly", "definition": "Noisy and lacking in restraint or discipline; unwilling to submit to authority" },
    { "word": "Unscrupulous", "definition": "Without scruples or principles" },
    { "word": "Unseemly", "definition": "Not in keeping with accepted standards of what is right or proper in polite society" },
    { "word": "Unstinting", "definition": "Very generous" },
    { "word": "Untenable", "definition": "Incapable of being defended or justified" },
    { "word": "Untoward", "definition": "Unfavorable; inconvenient" },
    { "word": "Untrammeled", "definition": "Not confined or limited" },
    { "word": "Unviable", "definition": "Not able to work, survive, or succeed" },
    { "word": "Upbraid", "definition": "To reproach; to scold" },
    { "word": "Urbane", "definition": "Showing a high degree of refinement and the assurance that comes from wide social experience" },
    { "word": "Vacillate", "definition": "Be undecided about something; waver between conflicting positions or courses of action" },
    { "word": "Vacuous", "definition": "Devoid of intelligence, matter, or significance" },
    { "word": "Vanquish", "definition": "Come out better in a competition, race, or conflict" },
    { "word": "Variance", "definition": "The quality of varying" },
    { "word": "Vaunted", "definition": "Highly or widely praised or boasted about" },
    { "word": "Vehement", "definition": "Marked by extreme intensity of emotions or convictions" },
    { "word": "Venality", "definition": "The condition of being susceptible to bribes or corruption" },
    { "word": "Veneer", "definition": "A thin superficial layer that hides the underlying substance" },
    { "word": "Venerate", "definition": "To respect deeply" },
    { "word": "Venial", "definition": "Easily excused or forgiven; pardonable" },
    { "word": "Veracious", "definition": "Truthful" },
    { "word": "Verisimilitude", "definition": "The appearance of truth" },
    { "word": "Veritable", "definition": "Truthfully, without a doubt" },
    { "word": "Vicarious", "definition": "Felt or undergone as if one were taking part in the experience or feelings of another" },
    { "word": "Vicissitude", "definition": "Change in one’s circumstances, usually for the worse" },
    { "word": "Vie", "definition": "Compete for something" },
    { "word": "Vilify", "definition": "Spread negative information about" },
    { "word": "Vindicate", "definition": "To clear of accusation, blame, suspicion, or doubt with supporting arguments or proof" },
    { "word": "Vindictive", "definition": "Having a strong desire for revenge" },
    { "word": "Virago", "definition": "An ill-tempered or violent woman" },
    { "word": "Vitriol", "definition": "Abusive or venomous language used to express blame or bitter deep-seated ill will" },
    { "word": "Vitriolic", "definition": "Harsh or corrosive in tone" },
    { "word": "Vituperate", "definition": "To criticize harshly; to berate" },
    { "word": "Vociferous", "definition": "Conspicuously and offensively loud; given to vehement outcry" },
    { "word": "Volubility", "definition": "The quality of talking or writing easily and continuously" },
    { "word": "Voracious", "definition": "Very hungry; approaching an activity with gusto" },
    { "word": "Wanting", "definition": "Lacking" },
    { "word": "Wanton", "definition": "Showing no moral restraints to one's anger, desire, or appetites" },
    { "word": "Wax", "definition": "To gradually increase in size or intensity" },
    { "word": "Whimsical", "definition": "Determined by impulse or whim rather than by necessity or reason" },
    { "word": "Winsome", "definition": "Charming in a childlike or naive way" },
    { "word": "Zeitgeist", "definition": "Spirit of the times" },
    { "word": "Zenith", "definition": "The highest point; culmination" }
].sort((a, b) => a.word.localeCompare(b.word));

  const filteredWords = vocabularyWords.filter(word =>
    word.word.toLowerCase().includes(searchTerm.toLowerCase()) ||
    word.definition.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      <div className="container mx-auto px-4 py-8 mt-16">
        <h1 className="text-3xl font-bold mb-6">GRE Vocabulary</h1>
        
        <div className="grid grid-cols-1 gap-6 items-center">
          <Card>
          <CardHeader className="flex grid grid-cols-4">
            <div className = "">
              <CardTitle>Essential GRE Words</CardTitle>
              <div className="mt-4">
                <Input
                  type="search"
                  placeholder="Search words or definitions..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="max-w-sm"
                />
              </div>
            </div>
            <div className='float-right col-start-4 flow-root'>
                 <Button 
                    className="ml-4 float-right"
                    onClick={() => window.open("../../public/attachments/gre1000vocab.pdf", "_blank")}
                 >
                  Install Vocab PDF
                  </Button>  
            </div>
          </CardHeader>

            <CardContent>
              <ScrollArea className="h-[600px] pr-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                  {filteredWords.map((item) => (
                    <Card key={item.word} className="p-3 hover:shadow-md transition-shadow">
                      <h4 className="font-semibold text-sm text-primary mb-1">{item.word}</h4>
                      <p className="text-xs text-muted-foreground">{item.definition}</p>
                    </Card>
                  ))}
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default VerbalReasoning;