// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lslemdmkahxnvyzyzmfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbGVtZG1rYWh4bnZ5enl6bWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMTM2NzMsImV4cCI6MjA1MzY4OTY3M30.2KMY7qBpH78Yld6lNwcVwx1DcYGaZUHPq9T9njE-d-g";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);